package cloudstack

type Virtualmachine struct {
	Account               NullString      `json:"account"`
	Affinitygroup         []Affinitygroup `json:"affinitygroup"`
	Cpunumber             NullInt64       `json:"cpunumber"`
	Cpuspeed              NullInt64       `json:"cpuspeed"`
	Cpuused               NullString      `json:"cpuused"`
	Created               NullString      `json:"created"`
	Details               NullString      `json:"details"`
	Diskioread            NullInt64       `json:"diskioread"`
	Diskiowrite           NullInt64       `json:"diskiowrite"`
	Diskkbsread           NullInt64       `json:"diskkbsread"`
	Diskkbswrite          NullInt64       `json:"diskkbswrite"`
	Diskofferingid        ID              `json:"diskofferingid"`
	Diskofferingname      NullString      `json:"diskofferingname"`
	Displayname           NullString      `json:"displayname"`
	Displayvm             NullBool        `json:"displayvm"`
	Domain                NullString      `json:"domain"`
	Domainid              ID              `json:"domainid"`
	Forvirtualnetwork     NullBool        `json:"forvirtualnetwork"`
	Group                 NullString      `json:"group"`
	Groupid               ID              `json:"groupid"`
	Guestosid             ID              `json:"guestosid"`
	Haenable              NullBool        `json:"haenable"`
	Hostid                ID              `json:"hostid"`
	Hostname              NullString      `json:"hostname"`
	Hypervisor            NullString      `json:"hypervisor"`
	Id                    ID              `json:"id"`
	Instancename          NullString      `json:"instancename"`
	Isdynamicallyscalable NullBool        `json:"isdynamicallyscalable"`
	Isodisplaytext        NullString      `json:"isodisplaytext"`
	Isoid                 ID              `json:"isoid"`
	Isoname               NullString      `json:"isoname"`
	Keypair               NullString      `json:"keypair"`
	Memory                NullInt64       `json:"memory"`
	Name                  NullString      `json:"name"`
	Networkkbsread        NullInt64       `json:"networkkbsread"`
	Networkkbswrite       NullInt64       `json:"networkkbswrite"`
	Nic                   []Nic           `json:"nic"`
	Ostypeid              ID              `json:"ostypeid"`
	Password              NullString      `json:"password"`
	Passwordenabled       NullBool        `json:"passwordenabled"`
	Project               NullString      `json:"project"`
	Projectid             ID              `json:"projectid"`
	Publicip              NullString      `json:"publicip"`
	Publicipid            ID              `json:"publicipid"`
	Rootdeviceid          ID              `json:"rootdeviceid"`
	Rootdevicetype        NullString      `json:"rootdevicetype"`
	Securitygroup         []Securitygroup `json:"securitygroup"`
	Serviceofferingid     ID              `json:"serviceofferingid"`
	Serviceofferingname   NullString      `json:"serviceofferingname"`
	Servicestate          NullString      `json:"servicestate"`
	State                 NullString      `json:"state"`
	Tag                   []Tag           `json:"tags"`
	Templatedisplaytext   NullString      `json:"templatedisplaytext"`
	Templateid            ID              `json:"templateid"`
	Templatename          NullString      `json:"templatename"`
	Vgpu                  NullString      `json:"vgpu"`
	Zoneid                ID              `json:"zoneid"`
	Zonename              NullString      `json:"zonename"`
}
