package cloudstack

type Volume struct {
	Account                    NullString `json:"account"`
	Attached                   NullString `json:"attached"`
	Chaininfo                  NullString `json:"chaininfo"`
	Created                    NullString `json:"created"`
	Destroyed                  NullBool   `json:"destroyed"`
	Deviceid                   ID         `json:"deviceid"`
	DiskBytesReadRate          NullInt64  `json:"diskbytesreadrate"`
	DiskBytesWriteRate         NullInt64  `json:"diskbyteswriterate"`
	DiskIopsReadRate           NullInt64  `json:"diskiopsreadrate"`
	DiskIopsWriteRate          NullInt64  `json:"diskiopswriterate"`
	Diskofferingdisplaytext    NullString `json:"diskofferingdisplaytext"`
	Diskofferingid             ID         `json:"diskofferingid"`
	Diskofferingname           NullString `json:"diskofferingname"`
	Displayvolume              NullBool   `json:"displayvolume"`
	Domain                     NullString `json:"domain"`
	Domainid                   ID         `json:"domainid"`
	Hypervisor                 NullString `json:"hypervisor"`
	Id                         ID         `json:"id"`
	Isextractable              NullBool   `json:"isextractable"`
	Isodisplaytext             NullString `json:"isodisplaytext"`
	Isoid                      ID         `json:"isoid"`
	Isoname                    NullString `json:"isoname"`
	Maxiops                    NullInt64  `json:"maxiops"`
	Miniops                    NullInt64  `json:"miniops"`
	Name                       NullString `json:"name"`
	Path                       NullString `json:"path"`
	Project                    NullString `json:"project"`
	Projectid                  ID         `json:"projectid"`
	Quiescevm                  NullBool   `json:"quiescevm"`
	Serviceofferingdisplaytext NullString `json:"serviceofferingdisplaytext"`
	Serviceofferingid          ID         `json:"serviceofferingid"`
	Serviceofferingname        NullString `json:"serviceofferingname"`
	Size                       NullInt64  `json:"size"`
	Snapshotid                 ID         `json:"snapshotid"`
	State                      NullString `json:"state"`
	Status                     NullString `json:"status"`
	Storage                    NullString `json:"storage"`
	Storageid                  ID         `json:"storageid"`
	Storagetype                NullString `json:"storagetype"`
	Tag                        []Tag      `json:"tags"`
	Templatedisplaytext        NullString `json:"templatedisplaytext"`
	Templateid                 ID         `json:"templateid"`
	Templatename               NullString `json:"templatename"`
	Type                       NullString `json:"type"`
	Virtualmachineid           ID         `json:"virtualmachineid"`
	Vmdisplayname              NullString `json:"vmdisplayname"`
	Vmname                     NullString `json:"vmname"`
	Vmstate                    NullString `json:"vmstate"`
	Zoneid                     ID         `json:"zoneid"`
	Zonename                   NullString `json:"zonename"`
}
